site_name: IC - IA e Cybersecurity
repo_url: https://github.com/Fiddelis/inatel-ic-morpheus
repo_name: fiddelis/inatel-ic-morpheus
extra:
  homepage: http://fiddelis.me/inatel-ic-morpheus/
  analytics:
    provider: google
    property: G-JCXV5HL48C
    
theme:
  language: pt-BR
  favicon: assets/favicon.png
  logo: assets/favicon.png
  name: material
  features:
    - content.code.copy
    - navigation.instant.progress
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    
markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_css:
  - css/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css