site_name: Estudos
repo_url: https://github.com/Fiddelis/inatel-ic-morpheus
repo_name: fiddelis/inatel-ic-morpheus

extra:
  homepage: http://fiddelis.me/inatel-ic-morpheus/
  analytics:
    provider: google
    property: G-JCXV5HL48C

theme:
  language: pt-BR
  favicon: assets/favicon.png
  logo: assets/favicon.png
  name: material
  features:
    - header.autohide
    - navigation.footer
    - content.code.copy
    - navigation.instant.progress
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Fiddelis
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/lucas-ruan-fidelis/

extra_css:
  - css/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css